export const Config = {

  // imgUrl: 'https://pad.protic.site/wp-content/uploads/pad-portrait',
  // imgUrlExt: 'png',

  imgThumbnailUrl: 'https://gamewith.akamaized.net/article_tools/pad/gacha',
  imgThumbnailUrlExt: 'png',

  imgUrl: 'http://www.puzzledragonx.com/en/img/book',
  imgUrlExt: 'png',

  dragAndDropType: 'monster',

  potentialAwokenLength: {
    'HP強化': 1,
    '攻撃強化': 1,
    '回復強化': 1,
    '自動回復': 1,
    '操作時間延長': 1,
    '火ダメージ軽減': 1,
    '水ダメージ軽減': 1,
    '木ダメージ軽減': 1,
    '光ダメージ軽減': 1,
    '闇ダメージ軽減': 1,
    'スキル遲延耐性': 1,
    '全パラメータ強化': 2,
    '神キラー': 2,
    'ドラゴンキラー': 2,
    '悪魔キラー': 2,
    'マシンキラー': 2,
    'バランスキラー': 2,
    '攻撃キラー': 2,
    '体力キラー': 2,
    '回復キラー': 2,
    'HP強化＋': 2,
    '攻撃強化＋': 2,
    '回復強化＋': 2,
    '操作時間延長＋': 2,
    '進化用キラー': 2,
    '能力覺醒用キラー': 2,
    '強化合成用キラー': 2,
    '売却用キラー': 2,
    '火ダメージ軽減＋': 2,
    '水ダメージ軽減＋': 2,
    '木ダメージ軽減＋': 2,
    '光ダメージ軽減＋': 2,
    '闇ダメージ軽減＋': 2,
    '属性吸収貫通': 6,
    'ダメージ無効貫通': 6,
    '毒目覚め耐性': 6,
    'お邪魔目覚め耐性': 6,
    'リーダーチェンジ耐性': 6,
    'ダメージ吸収貫通': 6,
    '消せないドロップ回復': 6,
    'ルーレット回復': 6,
  }
};